import { IKeyCodes } from '@/utils/types'

export const KEYS: IKeyCodes = {
	81: {
		char: 'С4',
		color: '#E81224',
		note: ['do'],
		audio: 'do',
		active: false,
	},
	50: {
		char: 'С4#',
		color: '#8764B8',
		note: ['do#', 're&'],
		audio: 'do_',
		active: false,
	},
	87: {
		char: 'D4',
		color: '#F7630C',
		note: ['re'],
		audio: 're',
		active: false,
	},
	51: {
		char: 'D4#',
		color: '#6E442F',
		note: ['re#', 'mi&'],
		audio: 're_',
		active: false,
	},
	69: {
		char: 'E4',
		color: '#FFF100',
		note: ['mi'],
		audio: 'mi',
		active: false,
	},
	82: {
		char: 'F4',
		color: '#16C60C',
		note: ['fa'],
		audio: 'fa',
		active: false,
	},
	53: {
		char: 'F4#',
		color: '#BAD80A',
		note: ['fa#', 'sol&'],
		audio: 'fa_',
		active: false,
	},
	84: {
		char: 'G4',
		color: '#0078D7',
		note: ['sol'],
		audio: 'sol',
		active: false,
	},
	54: {
		char: 'G4#',
		color: '#F03A17',
		note: ['sol#', 'la&'],
		audio: 'sol_',
		active: false,
	},
	89: {
		char: 'A4',
		color: '#886CE4',
		note: ['la'],
		audio: 'la',
		active: false,
	},
	55: {
		char: 'A4#',
		color: '#757575',
		note: ['la#', 'si&'],
		audio: 'la_',
		active: false,
	},
	85: {
		char: 'B4',
		color: '#8E562E',
		note: ['si'],
		audio: 'si',
		active: false,
	},
	86: {
		char: 'C5',
		color: '#E81224',
		note: ['do2'],
		audio: 'do2',
		active: false,
	},
	71: {
		char: 'C5#',
		color: '#5C2E91',
		note: ['do2#', 're2&'],
		audio: 'do2_',
		active: false,
	},
	66: {
		char: 'D5',
		color: '#F7630C',
		note: ['re2'],
		audio: 're2',
		active: false,
	},
	72: {
		char: 'D5#',
		color: '#824F2E',
		note: ['re2#', 'mi2&'],
		audio: 're2_',
		active: false,
	},
	78: {
		char: 'E5',
		color: '#FFF100',
		note: ['mi2'],
		audio: 'mi2',
		active: false,
	},
	77: {
		char: 'F5',
		color: '#16C60C',
		note: ['fa2'],
		audio: 'fa2',
		active: false,
	},
	75: {
		char: 'F5#',
		color: '#E4F577',
		note: ['fa2#', 'sol2&'],
		audio: 'fa2_',
		active: false,
	},
	188: {
		char: 'G5',
		color: '#0078D7',
		note: ['sol2'],
		audio: 'sol2',
		active: false,
	},
	76: {
		char: 'G5#',
		color: '#41B00C',
		note: ['sol2#', 'la2&'],
		audio: 'sol2_',
		active: false,
	},
}
